version: '2'

services:
 db:
  image:postgres
  restart:always
  environment:
    -POSTGRES_USER=postgres
    -POSTGRES_PASSWORD=passw0rd 
 server:
  build:./src
  command: bash -c "./run.sh"
  volumes:
   - data-volume:/var/log/erss
   - ./src:/code
  ports:
   - "12345:12345"
  tty: true

volumes:
  data-volume:	